CREATE TABLE employees
(
    employee_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name               VARCHAR(255)   NOT NULL,
    last_name                VARCHAR(255)   NOT NULL,
    position                 VARCHAR(255)   NOT NULL,
    salary                   DECIMAL(10, 2) NOT NULL,
    department_department_id BIGINT,
    FOREIGN KEY (department_department_id) REFERENCES departments (department_id)
);