CREATE TABLE IF NOT EXISTS users
(
    user_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name              VARCHAR(255) NOT NULL UNIQUE,
    password               VARCHAR(255) NOT NULL,
    role                   VARCHAR(50)  NOT NULL,
    is_account_non_locked BOOLEAN
);