CREATE TABLE IF NOT EXISTS books
(
    book_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    author           VARCHAR(255) NOT NULL,
    publication_year INT          NOT NULL
);

INSERT INTO books (title, author, publication_year)
VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 1954),
       ('Pride and Prejudice', 'Jane Austen', 1813),
       ('1984', 'George Orwell', 1949),
       ('To Kill a Mockingbird', 'Harper Lee', 1960),
       ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);