CREATE TABLE customers (
                           customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name VARCHAR(255) NOT NULL,
                           last_name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL,
                           contact_number VARCHAR(20)
);