CREATE TABLE orders (
                        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        order_date DATE NOT NULL,
                        shipping_address VARCHAR(255) NOT NULL,
                        total_price DECIMAL(10, 2) NOT NULL,
                        order_status VARCHAR(255) NOT NULL,
                        FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);