CREATE TABLE IF NOT EXISTS order_product
(
    order_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT  NOT NULL,
    product_id       BIGINT  NOT NULL,
    quantity         INTEGER NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (order_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id)
);