CREATE TABLE IF NOT EXISTS orders
(
    order_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_price DECIMAL(19, 2) NOT NULL,
    status      VARCHAR(255)   NOT NULL,
    user_id     BIGINT,
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);