spring.application.name=SpringMVCWithObjectMapper

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/DBforMapper
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.hikari.schema=public
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public
