spring.application.name=SpringSecurityWithJWT

jwt.secret = mySuperSecretKeyWithAtLeast32Characters1234567890
jwt.expirationMs = 3600000
jwt.refreshExpirationMs = 604800000

spring.datasource.url=jdbc:postgresql://localhost:5432/DBforJWT
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.hikari.schema=public
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public

logging.level.org.springframework.security=TRACE

server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
server.ssl.enabled=true

logging.file.name=application.log
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n